### PR TITLE
use big-json for report generation

### PR DESCRIPTION
**Pull request by owens-ben**

### CODE REVIEW

**Comment by owens-ben** [comment]
@rpii hopefully this is all good. Highly recommend you test it on your end, while it works on mine its clear different shapes / sizes of JSON files can cause issues.

**Comment by owens-ben** [comment]
@rpii hopefully this is all good. Highly recommend you test it on your end, while it works on mine its clear different shapes / sizes of JSON files can cause issues.

**Comment by rpii** [comment]
So are you thinking that the stringify in HtmlReporter is ok?  You had
deleted those before.

We can remove those if necessary.

Rich

**Comment by owens-ben** [comment]
> So are you thinking that the stringify in HtmlReporter is ok? You had deleted those before. We can remove those if necessary. Rich
> […](#)


Yes, those are fine. The only error I had was that it was JSON.stringify, no line number. I had to eliminate them one by one until I found the culprit. I think they're fine for debugging. That's why I closed the original PR, I forgot I had those extraneous changes.

Also just wondering when you'll release the new version?

**Comment by rpii** [comment]
working through it now,
trying to run my test cases.   I am currently getting empty report.json
files.  Havent had time to debug it yet.

I will release it as soon as I can

Rich

**Comment by rpii** [comment]
Ben,

Ive got it working.  had to make a few changes,  the stream read needs to
finish or partial files happen.
I committed it.  go ahead and pull and test.  it should work.  passed my
tests,  but I dont have a huge one test test.

Rich

**Comment by owens-ben** [comment]
@rpii all good! Would be great if you could release ASAP

**Comment by rpii** [comment]
I published it.  no chance to check that out.

Rich

**Pull request merged**
